[build]
  base = "documentation"
  publish = "build"
  command = "npm ci && npm run build"
 
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

 
# Production deploy
[context.production.environment]
  NODE_ENV = "production"
 
# Preview deploys (Pull Requests)
[context.deploy-preview]
  command = "npm ci && npm run build"
[context.deploy-preview.environment]
  NODE_ENV = "development"
  BASE_URL='/' 