[build]
  base = "documentation"
  publish = "documentation/build"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18.20.3"
  NPM_FLAGS = "--legacy-peer-deps"

[context.deploy-preview.environment]
  NODE_ENV = "development"
